[package]
name = "emnify_hose"
version = "0.1.0"
authors = ["Zoran Zaric <zz@zoranzaric.de>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
serde_json = "1.0"
tokio-core = "0.1"
rand = "0.3.18"
